export const mockStakingParams = {
  status: "success",
  isLoading: false,
  isSuccess: true,
  isError: false,
  isIdle: false,
  data: {
    unbonding_time: 432000,
    max_validators: 100,
    max_entries: 7,
    historical_entries: 10000,
    bond_denom: "uluna",
  },
  dataUpdatedAt: 1681390327815,
  error: null,
  errorUpdatedAt: 0,
  failureCount: 0,
  errorUpdateCount: 0,
  isFetched: true,
  isFetchedAfterMount: true,
  isFetching: false,
  isRefetching: false,
  isLoadingError: false,
  isPlaceholderData: false,
  isPreviousData: false,
  isRefetchError: false,
  isStale: false,
}
